INSERT INTO TOOL(ID, CODE, TYPE, BRAND) VALUES (1, 'CHNS', 'CHAINSAW', 'Stihl');
INSERT INTO TOOL(ID, CODE, TYPE, BRAND) VALUES (2, 'LADW', 'LADDER', 'Werner');
INSERT INTO TOOL(ID, CODE, TYPE, BRAND) VALUES (3, 'JAKD', 'JACKHAMMER', 'DeWalt');
INSERT INTO TOOL(ID, CODE, TYPE, BRAND) VALUES (4, 'JAKR', 'JACKHAMMER', 'Ridgid');

INSERT INTO RENTAL_CHARGE(ID, TYPE, DAILY_CHARGE, WEEKDAY_CHARGE, WEEKEND_CHARGE, HOLIDAY_CHARGE) VALUES (1, 'LADDER', 1.99, 1, 1, 0);
INSERT INTO RENTAL_CHARGE(ID, TYPE, DAILY_CHARGE, WEEKDAY_CHARGE, WEEKEND_CHARGE, HOLIDAY_CHARGE) VALUES (2, 'CHAINSAW', 1.49, 1, 0, 1);
INSERT INTO RENTAL_CHARGE(ID, TYPE, DAILY_CHARGE, WEEKDAY_CHARGE, WEEKEND_CHARGE, HOLIDAY_CHARGE) VALUES (3, 'JACKHAMMER', 2.99, 1, 0, 0);